export type FontFace =
	string
	| "Accanthis ADF Std"
	| "Amatic SC"
	| "Arial"
	| "Arial (Legacy)"
	| "Balthazar"
	| "Bangers"
	| "Comic Neue Angular"
	| "Creepster"
	| "Denk One"
	| "Fondamento"
	| "Fredoka One"
	| "Gotham SSm"
	| "Grenze Gotisch"
	| "Guru"
	| "Highway Gothic"
	| "Inconsolata"
	| "Indie Flower"
	| "Josefin Sans"
	| "Jura"
	| "Kalam"
	| "Luckiest Guy"
	| "Merriweather"
	| "Michroma"
	| "Nunito"
	| "Oswald"
	| "Patrick Hand"
	| "Permanent Marker"
	| "Press Start 2P"
	| "Roboto"
	| "Roboto Condensed"
	| "Roboto Mono"
	| "Roman Antique"
	| "Sarpach"
	| "Source Sans Pro"
	| "Special Elite"
	| "Titillium Web"
	| "Ubuntu"
	| "Zekton"

return {
	["Accanthis ADF Std"] = "rbxasset://fonts/families/AccanthisADFStd.json",
	["Amatic SC"] = "rbxasset://fonts/families/AmaticSC.json",
	["Arial"] = "rbxasset://fonts/families/Arial.json",
	["Arial (Legacy)"] = "rbxasset://fonts/families/LegacyArial.json",
	["Balthazar"] = "rbxasset://fonts/families/Balthazar.json",
	["Bangers"] = "rbxasset://fonts/families/Bangers.json",
	["Comic Neue Angular"] = "rbxasset://fonts/families/ComicNeueAngular.json",
	["Creepster"] = "rbxasset://fonts/families/Creepster.json",
	["Denk One"] = "rbxasset://fonts/families/DenkOne.json",
	["Fondamento"] = "rbxasset://fonts/families/Fondamento.json",
	["Fredoka One"] = "	rbxasset://fonts/families/FredokaOne.json",
	["Gotham SSm"] = "rbxasset://fonts/families/GothamSSm.json",
	["Grenze Gotisch"] = "rbxasset://fonts/families/GrenzeGotisch.json",
	["Guru"] = "rbxasset://fonts/families/Guru.json",
	["Highway Gothic"] = "rbxasset://fonts/families/HighwayGothic.json",
	["Inconsolata"] = "	rbxasset://fonts/families/Inconsolata.json",
	["Indie Flower"] = "rbxasset://fonts/families/IndieFlower.json",
	["Josefin Sans"] = "rbxasset://fonts/families/JosefinSans.json",
	["Jura"] = "rbxasset://fonts/families/Jura.json",
	["Kalam"] = "rbxasset://fonts/families/Kalam.json",
	["Luckiest Guy"] = "rbxasset://fonts/families/LuckiestGuy.json",
	["Merriweather"] = "rbxasset://fonts/families/Merriweather.json",
	["Michroma"] = "rbxasset://fonts/families/Michroma.json",
	["Nunito"] = "rbxasset://fonts/families/Nunito.json",
	["Oswald"] = "	rbxasset://fonts/families/Oswald.json",
	["Patrick Hand"] = "rbxasset://fonts/families/PatrickHand.json",
	["Permanent Marker"] = "rbxasset://fonts/families/PermanentMarker.json",
	["Press Start 2P"] = "rbxasset://fonts/families/PressStart2P.json",
	["Roboto"] = "rbxasset://fonts/families/Roboto.json",
	["Roboto Condensed"] = "rbxasset://fonts/families/RobotoCondensed.json",
	["Roboto Mono"] = "rbxasset://fonts/families/RobotoMono.json",
	["Roman Antique"] = "rbxasset://fonts/families/RomanAntique.json",
	["Sarpanch"] = "rbxasset://fonts/families/Sarpanch.json",
	["Source Sans Pro"] = "rbxasset://fonts/families/SourceSansPro.json",
	["Special Elite"] = "rbxasset://fonts/families/SpecialElite.json",
	["Titillium Web"] = "rbxasset://fonts/families/TitilliumWeb.json",
	["Ubuntu"] = "rbxasset://fonts/families/Ubuntu.json",
	["Zekton"] = "rbxasset://fonts/families/Zekton.json",
}
